# Generated by Django 4.0.3 on 2022-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_car_data_km_alter_car_data_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
